### ISSUE TITLE
Create a plan for testing (AT and Production Validation)

### ISSUE THREAD

**Issue by vykster** [cal-itp/benefits#1193]
- [x] Draft AT Plan (review AT plan from courtesy card, create process for SacRT)
- [x] meet with dev team to create a plan for production validation (maybe involving SacRT staff)

**resources**
- [AT Courtesy Cards - valid user courtesy card flow](https://docs.google.com/spreadsheets/d/1WZdPBURZgPNXWndRkulKimab-S5aHASTacihuE3Qlrg/edit?usp=sharing) 
- [AT Template](https://docs.google.com/spreadsheets/d/1OLXOZvSmL03o7cwRSzrePDzQYKUqF11S6hE6y10SQ24/edit?usp=sharing)

**Comment by MarikoLochridge** [comment]
Here are the requested links, I also added them above. 

resources:

[UAT Courtesy Cards - valid user courtesy card flow](https://docs.google.com/spreadsheets/d/1WZdPBURZgPNXWndRkulKimab-S5aHASTacihuE3Qlrg/edit?usp=sharing)
[UAT Template](https://docs.google.com/spreadsheets/d/1OLXOZvSmL03o7cwRSzrePDzQYKUqF11S6hE6y10SQ24/edit?usp=sharing)

**Comment by machikoyasuda** [comment]
Clarifying these terms with clear meanings:

- **Acceptance Testing (AT)** - https://cal-itp.slack.com/archives/C013W8RUAMU/p1674772821341289
**AT**: Means the Cal-ITP team tests the application in test-benefits.calitp.org. It does not involve the client (like MST or SacRT employees). The goal of AT is for the Cal-ITP product managers to accept the work that the Cal-ITP engineers have delivered.

- **Production Validation** - https://cal-itp.slack.com/archives/C013W8RUAMU/p1674773174920159
**PV:** This must involve people at SacRT using real credit cards and payment validators.

**Comment by MarikoLochridge** [comment]
AT (Acceptance Testing): SacRT + senior benefits/Login.gov integration in Benefits[https://docs.google.com/spreadsheets/d/1DT7x84i89ccvN_fxd84E7toy9Rn-VgwJUAKD0v1ovME/edit?usp=sharing](url

**Comment by MarikoLochridge** [comment]
In our first round of AT for the SacRT + senior benefits/Login.gov integration we found that testers were stopped at the Little Pay integration point. 

https://cal-itp.slack.com/archives/C03V716MKQS/p1675124899668179?thread_ts=1674759150.261179&cid=C03V716MKQS 

Once this issue is sorted we will resume testing.

**Comment by MarikoLochridge** [comment]
In the second round of AT for the SacRT + senior benefits/Login.gov integration we found that testers were stopped at the Login.Gov integration point.

https://cal-itp.slack.com/archives/C03V716MKQS/p1675124899668179?thread_ts=1674759150.261179&cid=C03V716MKQS

Once this issue is sorted we will resume testing.
<img width="723" alt="Screen Shot 2023-01-31 at 3 09 31 PM" src="https://user-images.githubusercontent.com/115111446/215904318-39aff9cd-8207-47af-a35b-bb0e8740c849.png">

**Comment by MarikoLochridge** [comment]
This ticket was intended for the planning of Acceptance Testing and Production Validation.However for completion of Acceptance Testing & Production Validation new tickets have been created because Production Validation depends on Acceptance Testing being done, so they need separate tickets.

For next steps please see the following tickets. 

[Complete Acceptance Testing](https://github.com/cal-itp/benefits/issues/1239)
 
[Complete Production Validation] (https://github.com/cal-itp/benefits/issues/1240)

For future reference the flow is: 

Draft Acceptance Plan (review previous AT plans in order to improve process)
Draft Production Validation Plan (review previous PV plans in order to improve process, involve agency staff as needed)

**Comment by vykster** [comment]
@MarikoLochridge GH tip, to quickly link to new GH issues type hashtag then the issue number and GH will automatically include the issue title and a link.  If you pause after you type the hashtag it will pull up a tiny interactive list and you can type any text to match part of the title and select. 

Screenshot of the latter feature:


<img width="727" alt="Screenshot 2023-02-03 at 1 40 04 PM" src="https://user-images.githubusercontent.com/4284662/216681685-1fd9bcd8-17dd-4b3a-8ae1-21b64855c00e.png">

**Comment by MarikoLochridge** [comment]
@vykster #1240 is ongoing (Did I do that right?)
