### ISSUE TITLE
Add back button to eligibility index

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1203]
Once the agency selector modal from #1197 is complete, we want to give a user the ability to go back and select a different agency after having made an initial selection.

This should build on the "Previous page" button/include from #1025

## Acceptance Criteria

- [ ] On `/eligibility`, when the user enters _having selected an agency via the modal_, there is a "Previous page" button that takes the user back to the app homepage `/`

**Comment by thekaveman** [comment]
@angela-tran I think we still need to get this in

**Comment by angela-tran** [comment]
@thekaveman Sorry it's a bit confusing. The code changes from #1211 are in `dev` (https://github.com/cal-itp/benefits/commit/c82e52c39fa8b5cf79c3c7eea8ec10d325d4adb0), and this ticket is done.

I had enabled auto-merge on #1211, @machikoyasuda approved the PR, and then that merge commit was made to `dev`. However the PR itself wasn't marked as "Merged" but instead stayed open and said there was a merge conflict with `dev` (because of the merge commit). Seems like a GitHub bug.

**Comment by angela-tran** [comment]
I'll close out this ticket

**Comment by angela-tran** [comment]
![image](https://user-images.githubusercontent.com/25497886/215214839-0164d630-b07e-4204-bbc2-90bd9b4c2769.png)
