### ISSUE TITLE
Write down rollback procedure

### ISSUE THREAD

**Issue by afeld** [cal-itp/benefits#1249]
Currently, if we deploy a change to the app that makes it fail to start, we don't have a clear/defined way to undo that change to get the site up again.

## Acceptance Criteria

- [ ] There is a defined process for switching back to a known-good deployment if a new one fails

**Comment by afeld** [comment]
https://github.com/cal-itp/benefits/issues/1253 would potentially reduce the usefulness of this.

**Comment by angela-tran** [comment]
We need to write down what we would do to rollback a failed deployment

**Comment by thekaveman** [comment]
Now that #1527 is mostly done, I think this can be pretty straightforward:

1. Create a temporary branch from the last known good commit
4. Tag the HEAD of this branch with a release tag
5. Push the branch/tag to GitHub to kick off a release --> this is the "rollback"
6. Fix whatever issue is wrong using that branch
7. Merge into `main` for the next release

**Comment by angela-tran** [comment]
> 4. Fix whatever issue is wrong using that branch

Maybe I'm missing something, but if the branch was created from the last known good commit (or rather the last known [good release tag](https://github.com/cal-itp/benefits/pull/2270/files#r1704657141)?), then the issue wouldn't be present at that point, right?

The way I picture it is that we'd want to tag and push the last known good release tag so that the rollback is done / app is back in a good state, and then we would implement a fix from the commit that we were trying to release as a new PR. (And that commit would be the `HEAD` of `main`.)

**Comment by thekaveman** [comment]
Yeah that's a good point, my wording was muddy.
