### ISSUE TITLE
Investigate missing User Properties for Courtesy Cards in Amplitude events

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1338]
Follow up from #1229 which didn't fully resolve this issue.

For Courtesy Cards, we're still seeing blanks in the `user_properties` for Eligibility Type, e.g. in our "Unique Users L7D" chart:

![Unique users  L7D](https://user-images.githubusercontent.com/1783439/228625576-0016430b-6977-42b4-8c6c-64eefb94c490.png)

## To Reproduce

1. Attempt to confirm eligibility as a Courtesy Card user for MST
2. View user properties as of the `started eligibility` event
3. See blank in `eligibility_types`

## Expected behavior

User properties should be updated to have the eligibility type set every time for every type

**Comment by machikoyasuda** [comment]
@thekaveman I checked this dashboard [Unique users - L7D, Benefits: KPI, (Prod) Benefits](https://analytics.amplitude.com/compiler/chart/93c50c3/edit/jhofa1i?source=copy+url) today and it looks different:

<img width="1088" alt="image" src="https://user-images.githubusercontent.com/3673236/230225973-d877065b-ed2e-4638-a620-a409e9e04c9e.png">

Not getting `none` anymore. Do I have the wrong link/checking the wrong dashboard?

**Comment by angela-tran** [comment]
@machikoyasuda You'll want to modify the conditions in the chart definition to be between 3/22/2023 - 3/29/2023 to match Kegan's chart

**Comment by machikoyasuda** [comment]
Investigation findings: After investigating this a bit further, I think this may be a bug in how the Amplitude dashboard is set up. 

- The PR for this fix #1229 was deployed as part of [Release 2023.03.1](https://github.com/cal-itp/benefits/releases/tag/2023.03.1) on 3/8/2023. We can expect the Amplitude change to be applied after that date. That is, all users who check eligibility and complete enrollment after 3/8 should have a `user_properties` with `eligibility_types`.
- The chart currently is set to show the `eligibility_types` of the `Most Recent Value`
<img width="412" alt="image" src="https://user-images.githubusercontent.com/3673236/230232304-f84e1bd6-0bd6-4374-a9b0-b508e2ba0e81.png"> Changing this to `All Values` or `Cross Property Values` might be better for the `Checked Eligibility` chart, because a single user could be checking multiple types (clicking Senior and then trying Courtesy Card, or vice versa). Using those 2 different settings instead, there aren't any more `none`s.

**Comment by thekaveman** [comment]
I was just looking at those properties of the chart too... I'm still not totally clear on what they mean. `All Values` seems like it could be correct, but when I chose `Cross Property Values` it did some weird combination of the CC/senior so I don't think that's right.

**Comment by machikoyasuda** [comment]
As [discussed on Slack yesterday](https://compilerla.slack.com/archives/C02GQ7AJXQE/p1680737232942019), we will keep an eye on this dashboard's eligibility and enrollment events to ensure there are no new events with `eligibility_types` set to `none`. But otherwise, we do *not* think there is a bug in the code. There have been at least one event in April with `courtesy_cards` set correctly. Closing this issue for now, and will re-open if there are new events with `eligibility_types` set to `none`
