### ISSUE TITLE
Update focus ring 

### ISSUE THREAD

**Issue by vykster** [cal-itp/benefits#1387]
Improve UI of default browser for focus ring, make a bold yellow. 

<img width="479" alt="image" src="https://user-images.githubusercontent.com/3673236/235732637-4b05b99f-15a3-4faa-b235-16794cbc2ebb.png">

## Acceptance criteria

- [ ] When user moves between components next item is highlight with new focus style

## Links to user research, designs and resources

 - [Figma components page](https://www.figma.com/file/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(Full-Application)?node-id=2%3A11&t=HqzGZ7SsWd6xqQ3S-1)

**Comment by machikoyasuda** [comment]
Hey @srhhnry, I started looking at the designs for this ticket b/c I wanted to get all my questions to you before you start your leave.

I see that the Figma designs show examples of the focus ring on:
- text link (including external links, footer and modal links)
- certain buttons (Previous Page button, Login.gov modal button, modal close X button)

But there are no focus ring examples for:
- standard primary blue button (like Continue, Go back, Spanish, etc.)
- radio input (Eligibility form)
- text input (Courtesy Card form)
- agency selector


These all currently have the browser standard light blue focus rings:
<img width="186" alt="image" src="https://github.com/cal-itp/benefits/assets/3673236/73fe2b8a-57b0-4a0e-a715-099b0ae9d599">
<img width="182" alt="image" src="https://github.com/cal-itp/benefits/assets/3673236/5d05f6ee-3088-42f1-878d-60dcfdde3a9f">
<img width="185" alt="image" src="https://github.com/cal-itp/benefits/assets/3673236/c9391edd-e8ec-40ca-b2e7-882273359ec0">
<img width="383" alt="image" src="https://github.com/cal-itp/benefits/assets/3673236/73a73447-06b2-4113-ac7e-413008afe99d">
<img width="723" alt="image" src="https://github.com/cal-itp/benefits/assets/3673236/690473af-5eee-4787-bae2-e8d506f7f40c">
<img width="755" alt="image" src="https://github.com/cal-itp/benefits/assets/3673236/4768681b-0d2b-4a33-9aab-d59a80bec315">


Were the omission of the primary action button, Español button, agency selector radio input and text input intentional? Or should the same yellow focus ring design be applied to those as well?

**Comment by srhhnry** [comment]
Omission was not intentional! Just my own lack of understanding that aspect of accessibility. I'll mock those elements up either Friday (tomorrow) or next week (and am adding design to this issue for easier tracking).

**Comment by srhhnry** [comment]
Focus ring is updated on all those components^ if that all looks good I think we can close this ticket @machikoyasuda

**Comment by machikoyasuda** [comment]
@srhhnry Figma updates look good! The only thing is, as I mentioned on Slack, the focus ring border radiuses _must_ match that of the element itself. If you're comfortable with that, I can implement the design with the 3px/2px `#FDB714` ring with matching border-radiuses.

**Comment by srhhnry** [comment]
Yes, definitely comfortable with that. But I also feel like I'm missing something--border radius (aka corner radius in Figma) is set to 8px for both the component and the focus ring. Is there another difference you're seeing? I'm curious about the translation to CSS.
