### ISSUE TITLE
Eligibility Start: Bullet copy for each EligibilityVerifier

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1441]
This issue is to update the copy for the highlighted bulleted section:

<img width="1357" alt="image" src="https://github.com/cal-itp/benefits/assets/3673236/beb8d0b9-f430-47ed-8355-8098475c2c00">

This bulleted section's copy is not stored in `EligibilityVerifier`, it's called in https://github.com/cal-itp/benefits/blob/5fba58473d191fb2911fee32af048311b7f2f7ff/benefits/eligibility/views.py#L111-L117

I think it should be covered in a separate issue and PR, b/c there's a bit going on.

_Originally posted by @machikoyasuda in https://github.com/cal-itp/benefits/issues/1427#issuecomment-1600277695_

**Comment by machikoyasuda** [comment]
Since the copy for this ticket is restricted to names of services, there is no Spanish translation necessary. We can consider this copy ticket to be ready for development, as the Spanish translations are ready (same as English).

![Image](https://github.com/cal-itp/benefits/assets/3673236/883e2064-a24d-4702-b1df-373dfd689b0e)

After talking with @indexing, we decided it would be best to get this ticket done in this current sprint, Sprint 6, so I've moved it into Sprint 6.
