### ISSUE TITLE
Clickable prototype: transit benefit enrollment pathway for low income Californians

### ISSUE THREAD

**Issue by indexing** [cal-itp/benefits#1461]

**Comment by srhhnry** [comment]
Link to screens can be [found here](https://www.figma.com/file/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(Full-Application)?type=design&node-id=5281-19859&mode=design)

**Comment by srhhnry** [comment]
Basic Screens include:

- CalFresh option on /eligibility with information on expiration and eligibility
- CalFresh start page modeled on Older Adult page with no changes
- CalFresh success page with new information on when the benefit expires 

Stretch or Optional screens include

- All of the above + link on CalFresh success page for modal to collect user data in order to provide a notification
- Modal that collects user email in order to provide a notification
- Email notification (30 days before expiration)

**Comment by srhhnry** [comment]
Prototype [can be found here](https://www.figma.com/proto/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(Full-Application)?page-id=5281%3A19859&type=design&node-id=9889-91957&viewport=-1183%2C-236%2C0.1&t=iTopOMccQBFrX3l4-1&scaling=contain&starting-point-node-id=9889%3A91957&show-proto-sidebar=1&mode=design)

**Comment by srhhnry** [comment]
@vykster Do we want to include a link to a modal for more complex information (like what we have for Login.gov/contactless cards/identity verification) for this round of Calfresh screens (specifically to demo for CalFresh)? On that note do we want to include a section in the Help page?

**Comment by vykster** [comment]
I don't think the calfresh demo is as important as you deciding what you'd like to test with users. 

I think it's already enough for a good stakeholder demo and conversation.

**Comment by srhhnry** [comment]
Cool, okay, I'm going to add a modal in with some close approximation of text to test with users and we can choose to have it in the demo or not.

**Comment by srhhnry** [comment]
Prototype is complete and [located here. ](https://www.figma.com/proto/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(Full-Application)?page-id=5281%3A19859&type=design&node-id=9889-91957&viewport=-952%2C-153%2C0.06&t=Gz5CQYewZYD41BUe-8&scaling=scale-down&starting-point-node-id=9889%3A91957&show-proto-sidebar=1&hotspot-hints=0&hide-ui=1)
