### ISSUE TITLE
External Link Icon - Add external link icon to Footer link(s)

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1471]

**Comment by angela-tran** [comment]
Apparently, only some properties can be styled for the `:visited` pseudo-class selector (see [this CSS-tricks article](https://css-tricks.com/almanac/selectors/v/visited/)). This means that we can't just specify the `background-image` to use for a visited link.

This issue is more obvious with the footer links since they are `a` elements as opposed to our modal triggers which are `button`s styled as links.

### Compare visited `a` vs. visited `button`
![image](https://github.com/cal-itp/benefits/assets/25497886/1267e805-d02e-494d-b991-02666eef34f3)

![image](https://github.com/cal-itp/benefits/assets/25497886/d5e65966-c887-450a-b43e-adb69eb75c0d)

I found [a StackOverflow post](https://stackoverflow.com/questions/43099903/how-can-i-set-different-icons-for-visited-and-unvisited-external-links-with-css) with some links to ways to hack around `:visited`, but maybe we should discuss with the design team on what to do.
