### ISSUE TITLE
Refactor templates and includes

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1528]
This should follow the completion of #1442.

The results of #1442 and related efforts are to create many more template includes, template variables, and generally move more display to the templates (the goal!)

We opted to take an incremental approach and not worry about being super DRY, mostly focusing on getting the translation strings into templates and not as much template or include structure and what we were repeating.

This task is to go back to the templates and look for opportunities to cleanup:

* [ ] `base.html` and other `core` template structure
* [ ] flow or agency specific template structure
* [ ] error page template structure
* [ ] the many `{% include %}` templates structure
* [ ] button templates and styles

**Comment by machikoyasuda** [comment]
One thing we can do: Now that the app officially doesn't have anymore text next to call to action buttons, we can delete this whole section from `base.html` -

https://github.com/cal-itp/benefits/blob/dev/benefits/core/templates/core/base.html#L87
<img width="1093" alt="image" src="https://github.com/cal-itp/benefits/assets/3673236/c563e292-af81-40e8-be13-7c861a385f75">

**Comment by machikoyasuda** [comment]
While going through the app's typography, I noticed that there is 1 that does not have proper h1, h2, h3 ordering. Enrollment Index goes from H1 (the heading) to H3 (the Media Item title). On other page that uses Media Item, Eligibility Start, there's a H2 in between the heading and the Media Items, so that one's okay with Media Item titles being H3s.

This is somewhat related to this issue, because it's related to how we're sharing code through the Media Items include across pages, but it might lead to a situation like this where we have to change one small thing to get valid HTML.

<img width="1512" alt="image" src="https://github.com/cal-itp/benefits/assets/3673236/7aa699fc-372f-4420-ad53-f2024b059ba3">

**Comment by machikoyasuda** [comment]
More to be deleted: https://github.com/cal-itp/benefits/blob/dev/benefits/core/templates/core/includes/form.html#L32

<img width="1105" alt="image" src="https://github.com/cal-itp/benefits/assets/3673236/f4a6a318-6a0e-4f37-9d17-e0de5d385625">

**Comment by machikoyasuda** [comment]
Delete, unused:
<img width="553" alt="image" src="https://github.com/cal-itp/benefits/assets/3673236/d4ff5468-8a79-4f4c-9694-40a94843f64a">

**Comment by thekaveman** [comment]
> While going through the app's typography, I noticed that there is 1 that does not have proper h1, h2, h3 ordering. Enrollment Index goes from H1 (the heading) to H3 (the Media Item title). On other page that uses Media Item, Eligibility Start, there's a H2 in between the heading and the Media Items, so that one's okay with Media Item titles being H3s.
> 
> This is somewhat related to this issue, because it's related to how we're sharing code through the Media Items include across pages, but it might lead to a situation like this where we have to change one small thing to get valid HTML.

This was fixed in #1976

**Comment by thekaveman** [comment]
This feels too generic of an issue and not something that is causing a direct problem right now. We can come back with more specific refactor issues if needed.
