### ISSUE TITLE
English copy QA on test-benefits.calitp.org

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1583]
Confirm English copy on dev-benefits.calitp.org matches the final copy.

**Comment by indexing** [comment]
We're inheriting the current English copy from the content audit earlier this year. We have made some small changes, such as #1704, and moving to agency-specific copy rather than configurable strings. We've also informally reviewed the English copy through multiple translations, etc. 

@kaveman **Thus, the English copy is ready for prod.** If we get feedback after release, we will evaluate and make any copy updates we accept in a release later this year.
