### ISSUE TITLE
Spanish copy QA on test-benefits.calitp.org

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1584]
Confirm Spanish copy on dev-benefits.calitp.org matches the final copy.

**Comment by indexing** [comment]
@vykster As part of the app copy update workflow, I have a step in which someone reviews the Spanish copy provided by our translators. Generally, @machikoyasuda and I feel the most recent round of Spanish translations from our vendor are much better than the initial translation, but it still is preferable to have someone review it in the context of the application. That person would need to a native speaker or neutral third-party Spanish-speaker that can bring "fresh eyes" to the copy.

Any thoughts on a good candidate?

cc // @thekaveman

**Comment by vykster** [comment]
@mrose914 would this be something you are willing to do?

**Comment by machikoyasuda** [comment]
@mrose914 test-benefits.calitp.org/ it's ready

**Comment by thekaveman** [comment]
@mrose914 here is the spreadsheet with the approved Spanish copy: https://docs.google.com/spreadsheets/d/1_Gi_YbJr4ZuXCOsnOWaewvHqUO1nC1nKqiVDHvw0118/edit#gid=610152150

**Comment by indexing** [comment]
@mrose914 In order to do a thorough review of the app, I've provided some guidance below. This approach adds some complexity to the process, but I don't see how you'll be able to see different aspects of the app in context without using test data. Feel free to jump directly to step 8 and review directly in the Copy master spreadsheet. It does include links to individual views for context.

Looking forward to your feedback on the Spanish copy as well as the process to review it. 
cc// @machikoyasuda 

--- 

# Instructions for reviewing Spanish translation of the Benefits app

To access various views in the app, you will need to follow several enrollment pathways in the application. Please do not use your personal accounts for Login.gov, ID.me, etc. to complete your review. We have a set of test accounts and test data available in [Benefits Test Data](using%20test%20data.). 

1. Open the Benefits application in our test environment using a supported browser. <https://test-benefits.calitp.org/>

2. Switch the application language to Spanish using the button labeled *Español* on the right side of the app header.

3. Choose MST as your transit agency.

4. Follow the *Older Adult* enrollment pathway to completion using [test data](https://docs.google.com/document/d/1bFynuiLy9POXYEYnLVEQJpAm1TVqlappN9lU9ev3Bvg/edit?usp=sharing).

5. Follow the *Veterans* enrollment pathway to completion using [test data](https://docs.google.com/document/d/1bFynuiLy9POXYEYnLVEQJpAm1TVqlappN9lU9ev3Bvg/edit?usp=sharing).

6. Follow the *Courtesy Card* pathway to completion using [test data](https://docs.google.com/document/d/1bFynuiLy9POXYEYnLVEQJpAm1TVqlappN9lU9ev3Bvg/edit?usp=sharing).

7. Review the Help page.

8. Jot down any issues or notes during the review. Highlight any proposed changes on the *forTranslation* tab in the [Cal-ITP Benefits Application Copy](https://docs.google.com/spreadsheets/d/1_Gi_YbJr4ZuXCOsnOWaewvHqUO1nC1nKqiVDHvw0118/edit?usp=sharing) spreadsheet. Use the comment feature in Google Sheets to share your feedback. Please mention Andy Walker and Machiko Yasuda in each comment.

**Comment by machikoyasuda** [comment]
@mrose914 You do have to create it. We can't share sandbox accounts because you have to 2-factor auth with your phone and email.

**Comment by thekaveman** [comment]
You should be able to create one on your own without any requests, here: https://idp.int.identitysandbox.gov

**Comment by machikoyasuda** [comment]
@mrose914 For Veterans (as opposed to MST/Older Adult), you can use these credentials: https://github.com/department-of-veterans-affairs/vets-api-clients/blob/master/test_accounts/verification_test_accounts.md

**Comment by indexing** [comment]
@mrose914 Yes. This block of copy is on the "All Agencies" tab. I added the MST tab as well: https://docs.google.com/spreadsheets/d/1_Gi_YbJr4ZuXCOsnOWaewvHqUO1nC1nKqiVDHvw0118/edit#gid=1602799154&range=C4

**Comment by indexing** [comment]
I created two new issues to correct copy bugs that @mrose914 noted in her review.

- [ ] #1709 
- [ ] #1710 

The review is now complete, so I'm marking this issue closed. Thanks Marissa!
