### ISSUE TITLE
Make a new section on help page for Benefits source link

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1607]
Definitely want to hear @indexing's thoughts on content, but could see a header title that says something like: 

- About Cal-ITP software
- About Cal-ITP Benefits software
- About our software (less inclined toward this one as we don't use the first person in the app--e.g. you not we)
- Cal-ITP software policy ([looking to 18F here](https://18f.gsa.gov/open-source-policy/))
- Cal-ITP Benefits open source policy

I think either of the first two are my preference.

_Originally posted by @srhhnry in https://github.com/cal-itp/benefits/issues/1596#issuecomment-1660808260_

**Comment by thekaveman** [comment]
Initial assignment for @indexing to come up with the heading and final copy for this section.

**Comment by srhhnry** [comment]
Adding a design tag to track this in Figma when we make a decision on copy

**Comment by indexing** [comment]
@srhhnry @thekaveman Until we have a more robust, dedicated 'about' view in the Benefits app, here are my thoughts:

- Rather than create another section that will make this view longer, we add this additional string, "The Benefits application is Free and Open Source Software (FOSS). You may obtain the source code from Github." as the last item under the first question: What is Cal-ITP Benefits? 

![Screenshot 2023-08-07 at 4 13 14 PM](https://github.com/cal-itp/benefits/assets/6279581/907dc34c-5cfb-4167-a815-fe3fcc9e9bba)

**Comment by srhhnry** [comment]
Great idea @indexing!

**Comment by indexing** [comment]
@thekaveman @srhhnry I've added this string to the EN-US tab in the Master, so it can now be synced to Figma: 
https://share.getcloudapp.com/d5uDQ94k
