### ISSUE TITLE
Fix Return Home link on Eligibility Verification Failure screen

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1650]
From @srhhnry's Design QA doc:

> Return Home returns to Veteran Eligibility not the home page

@srhhnry this is the current behavior on Production. I don't know that we ever really defined it? At one point I think there were arrows going backwards on Figma but I'm not seeing that.

In any case, which page should the user go back to? All the way to the Index?

**Comment by srhhnry** [comment]
Yeah, I think I removed some of those lines back when we cleaned up links to the help page (during the modal design). Instead of re-adding those lines I just put a note in the dev board that all error screens direct back to the home page. This behavior can also be seen in either the desktop and mobile prototype. 

The rationale behind directing users to the home page is to give them the opportunity to correct either their agency selection or their benefit selection, in case those are the error issues. I believe this access outweighs the user having to make two clicks to get back to their preferred benefit flow. As the app becomes more complex, this is a good assumption to test.

**Comment by thekaveman** [comment]
> all error screens direct back to the home page

So in the case of an error with the Littlepay connection (hence the user has _already verified their eligibility_) we should still send them all the way back to the beginning, forcing a re-verification?

**Comment by thekaveman** [comment]
Based on conversation in stand-up, we're only going to adjust the Eligibility Failure flow back to the index page for now.

Follow-up tickets will come for more nuance on the additional error states/pages.
