### ISSUE TITLE
`Eligibility index`: update copy to be more consistent and provide context for user

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/benefits#2007]
| Desktop (showing MST) | Mobile (showing SBMTD) |
| --- | --- |
| ![image](https://github.com/cal-itp/benefits/assets/25497886/fc0aea1c-832f-4375-b1ba-ea77f1f9f306) | ![image](https://github.com/cal-itp/benefits/assets/25497886/1e78192e-7852-46f3-91c4-1324e48d8238) |

## Figma links
- [Desktop_Eligibility](https://www.figma.com/file/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(Full-Application)?type=design&node-id=14387-12551&mode=design&t=11PIPi0dRtWNuQmK-4)
- [Mobile_Eligibility](https://www.figma.com/file/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(Full-Application)?type=design&node-id=14646-18505&mode=design&t=11PIPi0dRtWNuQmK-4)

## Acceptance Criteria

- [x] Body copy: first body sentence was updated
- [x] Remove agency name in the copy for the radio buttons subheaders
   - [x] “MST Courtesy Card” is now “Courtesy Card”
   - [x] "SBMTD Reduced Fare Mobility ID" is now "Reduced Fare Mobility ID"
- [x] Radio button descriptions were updated and for SBMTD, mentions the previous name
- [x] CTA copy is updated

**Comment by angela-tran** [comment]
Hi @sarah @andy - I noticed that the Figma design for this screen (Eligibility Index) shows that the casing on the CTA is now sentence case ("Choose your benefit") instead of the current mixed case ("Choose your Benefit"). And actually, all screens that were updated for this Agency Card UX improvement effort have sentence casing on their CTAs.

<img src="https://github.com/cal-itp/benefits/assets/25497886/8a933d92-f8ab-49b9-93c7-2dd8747c6f59" width="400">
<img src="https://github.com/cal-itp/benefits/assets/25497886/3d9059fe-11d7-4531-b91b-2fc731233e8b" width="400">

<br>
<br>
Within the "Agency Flow" page in Figma, the only screen that doesn't fit this pattern is the Home Page; its CTA casing is title case ("Get Started").
<br>
<img src="https://github.com/cal-itp/benefits/assets/25497886/4438d2ed-5827-43c5-9d1c-352cd22bc58b" width="350">

<br>
<br>
The current, live Benefits app uses a mix of title case and sentence case for its CTAs (e.g. the current site uses "Get Started" on the agency-specific home page, "Choose your Benefit" on the Eligibility index page, "Connect your Card" on the Enrollment index page, "Check your eligibility" on the Eligibility confirm page).

<img src="https://github.com/cal-itp/benefits/assets/25497886/da03ffe4-14b7-497d-88b5-75cca38d17e1" width="450">
<img src="https://github.com/cal-itp/benefits/assets/25497886/d1049443-411a-499f-8f79-9042354044bd" width="450"> 


<br>
<br>
We didn't talk about changing any casing during hand-off, so could you help clarify the reason for this discrepancy between Figma and the current site with regards to CTA casing? Maybe the reason is something like one of these below?

- "The casing change is intentional, and we just forgot to mention it during hand-off. It should be done for the screens shown in 'Agency flow' in Figma. Do not touch the CTA casing on other pages."

- "The casing change is intentional, but not as a part of Agency Card UX improvement. It will be a part of a separate effort to normalize casing within all of the Benefits app. For these 'Agency flow' screens in Figma, we forgot to revert it back to what the current site shows."

- "This casing change was just an idea that we were playing around with while designing, and we decided against it for now and forgot to revert it back to what the current site shows."

I realize that relatively speaking, the CTA casing is a pretty small detail, but when I see a discrepancy like this, all these possible reasons run through my mind so it'd be helpful to get clarification.

**Comment by srhhnry** [comment]
I think @indexing can speak more to the casing as part of this effort versus others, but yes, the design of it is intentional (and we did forget to mention that!). Moving forward any new and redesigned screens will be in sentence case, as a sort of catch up of design debt. 

The home page is really only in the agency flow to demonstrate the full flow. There are no changes to the home page at this time.

**Comment by indexing** [comment]
@angela-tran Thanks for surfacing this question. As Sarah notes, moving to sentence case is definitely an intentional change, but one we did not discuss during handoff. 

Since we are revisiting the majority of views in the agency card flow, I'd propose we make the change to sentence case on each button label in those views as part of this issue. As you note, there is already inconsistency in the app now. Making changes to these labels gets us closer to consistent while we are already working in this aspect of the app with just a bit of additional effort. That said, if you feel these changes add too much to the scope for this sprint, we can address them separately.

The landing view is out of scope. We can address this label, along with all others that aren't using sentence case in a separate issue.

**Comment by angela-tran** [comment]
> Since we are revisiting the majority of views in the agency card flow, I'd propose we make the change to sentence case on each button label in those views as part of this issue.

> The landing view is out of scope. We can address this label, along with all others that aren't using sentence case in a separate issue.

Thanks @indexing - that all sounds good. I'll update all relevant tickets on the "[Improved UX for agency card enrollment](https://github.com/cal-itp/benefits/milestone/45)" milestone to include changing their button labels to use sentence case, and I'll leave any further ticket creation for other screens to be done later.
