### ISSUE TITLE
Secure critical Django cookies

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#201]
The following can be configured in [`settings.py`](https://github.com/cal-itp/benefits/blob/dev/benefits/settings.py).

Setting these ensures the cookies expire and are deleted when the user's browser closes (makes them session cookies)

* [x] [`CSRF_COOKIE_AGE`](https://docs.djangoproject.com/en/3.2/ref/settings/#csrf-cookie-age) = None
* [x] ~[`SESSION_COOKIE_AGE`](https://docs.djangoproject.com/en/3.2/ref/settings/#session-cookie-age) = None~
* [x] [`SESSION_EXPIRE_AT_BROWSER_CLOSE `](https://docs.djangoproject.com/en/3.2/ref/settings/#session-cookie-age) = True

We also want to prevent the CSRF cookie from being sent in cross-browser requests. E.g. a user clicks on a link to our site, from another site - in this case we don't want any previous CSRF cookie already in their browser sent. It's unlikely to be an issue in our app since there are no user logins etc. but for consistency with our other cookies (session and language).

* [x] [`CSRF_COOKIE_SAMESITE`](https://docs.djangoproject.com/en/3.2/ref/settings/#csrf-cookie-samesite) = "Strict"

**Comment by angela-tran** [comment]
Setting `CSRF_COOKIE_AGE` to `None` accomplishes what we want. 👍 

Setting `SESSION_COOKIE_AGE` to `None` however results in a `TypeError`:
![image](https://user-images.githubusercontent.com/25497886/142540185-0e661587-28b5-497e-b514-1552aa2b67bd.png)

I tried out setting it to 0, but then we have no session data 🤦 
![image](https://user-images.githubusercontent.com/25497886/142539787-e2b69a9d-667b-4e37-80ac-d238ba86c7e8.png)

It appears that [`SESSION_EXPIRE_AT_BROWSER_CLOSE`](https://docs.djangoproject.com/en/3.2/topics/http/sessions/#browser-length-sessions-vs-persistent-sessions) set to `True` is what we want.

I tried that out and verified that there is a new session cookie value when closing and re-opening my browser. 👍 

(It took me a while to realize that it was actually changing because for me, the `sessionid` cookie value is an array of length 3, where the first part doesn't seem to change much.)

![image](https://user-images.githubusercontent.com/25497886/142547794-0bced9e3-1b9d-425b-9158-f9f500635017.png)
