### ISSUE TITLE
reCAPTCHA: Remove reCAPTCHA icon and use link instead

### ISSUE THREAD

**Issue by machikoyasuda** [cal-itp/benefits#2494]
This ticket will need design, copy and product input, but I wanted to make the ticket here so we can start planning it out.

## Acceptance Criteria

- [x] Research: Can we remove the reCaptcha image? What is the exact requirement?
- [x] If the research says yes, we can remove the image, then onto design: Decide where to place ReCaptcha text. 

## Additional context

![Image](https://github.com/user-attachments/assets/9fd5ad3a-c0a6-4d05-9d20-a377fc5ef4ee)
Refer to how Login.gov does it with text here.

**Comment by machikoyasuda** [comment]
@indexing @thekaveman @angela-tran Put this ticket here as a stub. This was something we discussed when we first implemented reCaptcha. I then noticed a few days ago that Login.gov has a simple text sentence instead of the obnoxious image on the bottom right-hand side, so I wanted to make this ticket to remind us to look into whether we can make a similar change and make that change.

**Comment by thekaveman** [comment]
Design work for Sprint 11

**Comment by thekaveman** [comment]
Here's the Google reCAPTCHA FAQ on this topic: https://developers.google.com/recaptcha/docs/faq#id-like-to-hide-the-recaptcha-badge.-what-is-allowed

**Comment by srhhnry** [comment]
Current design direction: ![Image](https://github.com/user-attachments/assets/ba1402c9-a151-4a3c-81eb-35f34cd770f2)

This includes resizing the desktop and mobile CTA button to balance the page. The headline for the desktop screen was also justified to the left to help balance the page.

@thekaveman The product/design team discussed extending the approach of this form beyond the AC flow, so that all of the flows have the same template: large, centered CTA button that spans 4-6 bootstrap columns depending on breakpoint, left-justified header, no icons. For the dev team is it better to update one flow or all the flows at the same time?

**Comment by thekaveman** [comment]
@srhhnry 

> This includes resizing the desktop and mobile CTA button to balance the page. The headline for the desktop screen was also justified to the left to help balance the page.

> The product/design team discussed extending the approach of this form beyond the AC flow, so that all of the flows have the same template: large, centered CTA button that spans 4-6 bootstrap columns depending on breakpoint, left-justified header, no icons. For the dev team is it better to update one flow or all the flows at the same time?

All of these changes totally make sense, and yes I think we'd want to apply across every screen/flow. We'll just want to talk about how to split the changes out in terms of dev work and sequencing. If I understand, these are the list of changes you are proposing:

1. Left-justify headlines on desktop
2. Resize and center desktop and mobile CTA
3. Remove icons? _Need to know/see more about this_

Where 1 and 2 would be required before we can make this reCAPTCHA update -- is that correct?

**Comment by srhhnry** [comment]
Awesome! Regarding point number 3, here's a screenshot of a screen with the icons removed and the text readjusted so that everything on the page is within 3-4 columns depending on breakpoint

![Image](https://github.com/user-attachments/assets/467594bf-4f12-4766-b93b-c03aa99f61dc)

And no, we could certainly add in the Recaptcha language to the screens with forms without making these changes, but it just looks a bit sloppy: 

![Image](https://github.com/user-attachments/assets/708071b9-3341-45f7-9148-a2ee29c72977)

Since the page is fairly bare, there's not many places to place this text, which is why we have the flag in the first place (the text conflicts with the helper text already on the form).  So updating the page to accommodate the Recaptcha text is a nice change, but also helps us with making the app look more streamlined and consistent between breakpoints.

**Comment by machikoyasuda** [comment]
https://secure.login.gov/es

Este sitio está protegido por reCAPTCHA y se aplican la [Política de privacidad(abrir nueva pestaña)](https://policies.google.com/privacy?hl=es) y las [Condiciones de servicio(abrir nueva pestaña)](https://policies.google.com/terms?hl=es) de Google.

**Comment by srhhnry** [comment]
@indexing Can you figure out if we need to have Recaptcha on multiple pages?

**Comment by srhhnry** [comment]
The Recaptcha branch in Figma is merged and ready. The recaptcha text is in ditto as a component with spanish translation. Given that this is a formatting update there might be some weird little things when Ditto updates in Figma. I thiiiiiink I caught all of them, but let me know (today!) if there's anything that is obviously confusing and I'll see if there's a formatting error from the sync.

https://www.figma.com/design/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(Full-Application)?m=auto&node-id=15064-11387&t=gkak9CrbLqYJh8o6-1

I've left the Recaptcha text on both forms until we get clarity on whether we need them.
