### ISSUE TITLE
Implement sign out watcher for browser close

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#381]
## Background

We want to ensure the user is signed out of Login.gov when they close their browser window, at any point after having signed in. The browser closing deletes the app's (session) cookie, so the user's status from the app's perspective is also signed out. This is for the Login.gov system.

Coordinate with #368

See [comment below](https://github.com/cal-itp/benefits/issues/381#issuecomment-1094388712)

~### Resources~

~According to Mozilla, the [unload event should not be used](https://developer.mozilla.org/en-US/docs/Web/API/Window/unload_event#usage_notes) to watch for the browser being closed.~

~Instead, they suggest using [Document.visibilitychange](https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilitychange_event), or [Window.pagehide](https://developer.mozilla.org/en-US/docs/Web/API/Window/pagehide_event).~

~## Tasks~

* [ ] ~When the user is signed in (see #370), add script to the main layout to track browser close etc. (see notes above)~
* [ ] ~*TBD script should perform whatever is necessary per Login.gov*~

**Comment by afeld** [comment]
Curious: where this requirement is coming from? Makes sense to me that an explicit click of "logout" should log the user out of login.gov, but not sure that it is necessary/desirable to do so on browser close.

Thinking of the equivalent of a site using "Log in with Google" — I wouldn't want/expect closing of that site to log me out of Google.

**Comment by thekaveman** [comment]
@srhhnry can you weigh in from the UI/UX side, where this requirement came up in the design process?

**Comment by srhhnry** [comment]
Sure thing--so we're working on the assumption that Login.gov is likely a *new* or *new-ish* app for most users, and given how quickly we're moving on putting Benefits back up, we're trying out a low-context route first. This means we're trying to teach the user only a minimal amount about login.gov. This affects us in two core ways:

1. We're trying to ensure that any user at a public computer doesn't accidentally leave their login.gov account signed in. We could build out an additional screen asking the user to go back to login.gov to sign out, but that would mean a) more design + time spent describing the process and b) user error of going back to login.gov.

2. This first problem intersects with a second problem. We've added a link to the screens so that users can sign out of login.gov if they want to/need to.  HOWEVER, we'd also really like to discourage them from signing out before completing the process, so we've reduced the prominence of that sign out link.

So the automatic log out is a balance between ensuring users (especially public computer users) sign out, while also not encouraging them to do so at any point in the process.

**Comment by afeld** [comment]
Got it. Thanks for the quick and thorough explanation!

**Comment by thekaveman** [comment]
With the pure server-side implementation in #414, there really is no more need to watch and do something on browser close. 

The user's sign-in status with Login.gov is captured in their session cookie, which expires on browser close by definition. Since the access token from Login.gov is not stored anywhere or used beyond verifying that the user did sign-in, there is nothing to go back to Login.gov with, to sign the user out.

**Comment by thekaveman** [comment]
Putting this on hold as we work on the other log out piece in #375. This may not be needed anymore.

**Comment by thekaveman** [comment]
Closing, we won't be implementing this (it isn't possible without a redirect).

Instead we'll provide the user one last sign out button on the final success page, allowing them to manually terminate their Login.gov session. Otherwise it will time out according to their policies.
