### ISSUE TITLE
Re-configure OAuth `scope` setting for age verification

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#640]
## Background

In #598 we simplified the developer setup experience and runtime configuration by creating better defaults in `settings.py` and only using the environment / `.env` file for specific overrides.

Part of that effort saw the OAuth `scope` parameter move from an environment setting to be hard-coded in `settings.py`, which was fine for the basic IAL1 Single Sign-On use-case of #363.

We need to be able to send additional scopes for IAL2 / #635. So we need this setting to be configurable and not explicitly hard-coded to only the single `openid` scope.

## Additional context

The scope we need to send looks like `age_verification` or `age_verification:is_senior` for the specific Senior use-case. So in total we'll send two scopes (they are space separated):

```
openid age_verification:is_senior
```

## Thoughts

The additional scope is basically a stand-in for our `EligibilityType` in the [Eligibility Verification API Request](https://docs.calitp.org/eligibility-api/specification/#request). One approach could be to model needed scope(s) on the `EligibilityType` and inject into the OAuth request from the configured agency/verification type(s).

## Decision

* Use verifier's scope field when configuring the OAuth client
* See #678 for the definition of the scope field
* See #641 for how we'll verify eligibility

**Comment by angela-tran** [comment]
My thoughts here are focused on how to send the `scope` value and exactly where that value should come from.

### Simplest change: environment variable

Let's consider the smallest change that would make this work -- extracting out the hard-coded value as an environment variable. This would basically be to undo the [change from #598 that removed the `DJANGO_OAUTH_SCOPE` environment variable](https://github.com/cal-itp/benefits/pull/598/files#diff-d71405aa44f1e899a9cd920e5187aa1d02affdbd0da472eca95f814b0a8c1210L178).

The downside with this is it implies that this `scope` value, whatever it is, applies to any `EligibilityType` for any pair of `TransitAgency` and `EligibilityVerifier` that requires authentication.

This actually would not necessarily be wrong for the use case we're currently hoping to deploy - we would indeed have one `TransitAgency` with one `EligibilityVerifier` that requires authentication, and their intersection of supported `EligibilityType`s would be one type.

However, as soon as a new `scope` is required, we would have to scrap this. Should we assume that this is likely? If so, let's try to hedge for that.

### Hedge for needing more `scope`s in the future: model relationship between `scope` and `EligibilityType` and `EligibilityVerifier`

For context, notice that we currently read the OAuth client configuration and create the client at the top of `oauth/views.py`: https://github.com/cal-itp/benefits/blob/dev/benefits/oauth/views.py#L21. This will occur one time. If we model `scope` as a property related to `EligibilityType` and `EligibilityVerifier`, we would need to either 
 - be able to modify the `scope` on this client   
 or 
 - stop creating the client upfront and instead create one with the correct `scope` when we need it.

Assuming we can do that, I think a `scope` is unique to the combination of an `EligibilityType` and `EligibilityVerifier`.
**<details><summary>Explanation**
</summary>

 - It is not unique to _only_ an `EligibilityType` because multiple `EligibilityVerifier`s could reference a given `EligibilityType`. 
    - As a concrete example, let's say we had a `"senior"` type which has a `scope` of `"age_verification:is_senior`, and two `EligibilityVerifier`s -- one using Login.gov for authentication and the other using let's say Twitter. The scope would only make sense for the first verifier.
 - It is not unique to _only_ an `EligibilityVerifier` because if the `EligibilityVerifier` supports many `EligibiliityType`s, we wouldn't know which type the `scope` is associated to.
    - Concrete example: let's say we have a verifier that uses Login.gov for authentication and supports verifying `"senior"` and `"youth"`. If `scope` is on the verifier, we don't know which type it goes with.
</details>

I think one way we could model this is to introduce an `AuthenticationScope` model with a one-to-one relationship to `EligibilityType` and a one-to-one relationship to an `EligibilityVerifier`. In `oauth/views.py`, when we send the token request, we'll want to read the type and verifier from the session to figure out which scope to use.

### How to consume the user attribute that comes back

I'll write out my thoughts for this on #641.

**Comment by thekaveman** [comment]
It would actually be really helpful to have the refactored OAuth views from #668 for working on this change.

In that PR, the code that creates an OAuth Client was moved into a helper module/function, which should make the dynamic scope configuration here a little easier.
