### ISSUE TITLE
Update failure flows

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#643]
Epic #635 

- [x] Create screen and design flow for Eligibility Not Verified
- [x] Create screen and design flow for Payment not Verified
- [x] Verify error flow for Login.gov
- [x] Verify cancel flow for Login.gov

**Comment by srhhnry** [comment]
- [ ] Create screen and design flow for Eligibility Not Verified
- [ ] Create screen and design flow for Payment not Verified
- [ ] Verify error flow for Login.gov

**Comment by srhhnry** [comment]
Cancel flow is interesting--I'm assuming that means the user has decided to opt out of the login.gov flow by canceling from within the Login.gov site. In that case I believe we should direct them to the eligibility error screen, as it has a direct way to contact the agency (and my guess is cancellation will come because the process is too arduous or the user doesn't have the documents) and a link to the intro/home page with more information

Updated the Figma boards
![Image](https://user-images.githubusercontent.com/5394204/172922174-629644fb-f234-4397-8022-2727bb494ea7.png)

**Comment by srhhnry** [comment]
As for the error flow, the previous idea had been to direct the user back to the Get Started page. On further thought, I think we should also direct an errors in Login.gov to the same Eligibility error page. Given the length of the identity proofing flow, I feel like it's a good idea to give the user more information about what happened, even if it's vague (i.e. eligibility couldn't be verified). 

Updated the Figma board to reflect both of these pathways.

**Comment by thekaveman** [comment]
🙏 Thank you for these pathway arrows @srhhnry very helpful!

**Comment by srhhnry** [comment]
No problem! And really, there should be more! Now that I'm thinking about it, I'll add visualizations of the anchor links to the Help Page, as we're almost done there.
