### ISSUE TITLE
Engineering: Front-end - Eligibility Start page design: Redesign to a single-column design. Add media list.

### ISSUE THREAD

**Issue by machikoyasuda** [cal-itp/benefits#654]
- For both Mobile and Desktop, redesign the page to a two-column vertical design. 
- Redesign the 3-icon content page to be a 2-icon page and add the new bullet points of copy.
- Establish Mobile/Tablet width margins
- Make sure H1 font size is correct
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/3673236/172735521-c7b6760b-832d-448e-b45e-20f217debccb.png">
<img width="453" alt="image" src="https://user-images.githubusercontent.com/3673236/172735548-a9c6ed1f-23fd-4904-8e9f-629f6bf2eba1.png">

**Comment by thekaveman** [comment]
For this one, I think we want to modify the `eligibility:start` page and make sure the user is directed there right away - rather than moving all the UI into `core:agency_index`.

In #656 I think we will be adding a redirect in the [`core:agency_index` view](https://github.com/cal-itp/benefits/blob/dev/benefits/core/views.py#L57) to `eligibility:index`.

The [redirect that is already in `eligibility:index`](https://github.com/cal-itp/benefits/blob/dev/benefits/eligibility/views.py#L51) will then take the user to `eligibility:start`

## How it is now

```mermaid
graph LR
    A[core:index] -->|redirect| B(core:agency_index)
    B -->|user clicks button| C(eligiblity:index)
    C -->|redirect| D(eligibility:start)
```

## After #656 

```mermaid
graph LR
    A[core:index] -->|redirect| B(core:agency_index)
    B -->|*redirect*| C(eligiblity:index)
    C -->|redirect| D(eligibility:start)
```
