### ISSUE TITLE
Re-add option for running Cypress in a container

### ISSUE THREAD

**Issue by afeld** [cal-itp/benefits#681]
See discussion in https://github.com/cal-itp/benefits/pull/671.

## Acceptance Criteria

- [ ] With Docker installed, the Cypress tests can be run from the command line in (close to?) a single command

**Comment by angela-tran** [comment]
The closest I've gotten on this is to run the following (note that `%cd%` is for Windows, `$pwd` can be used for Mac/Linux?):
`docker run -it -v %cd%:/tests/cypress -v %cd%/../../fixtures:/fixtures -w /tests/cypress cypress/included:10.3.0`

It took me a few tries to get the volume mapping correct since we're using fixtures that are a few levels above our Cypress tests. The next thing to figure out is how to get the app running -- with the command I just mentioned, the tests are failing because of 404s.

I was referencing this article: https://www.cypress.io/blog/2019/05/02/run-cypress-with-a-single-docker-command/

**Comment by angela-tran** [comment]
I created a WIP branch here: https://github.com/cal-itp/benefits/compare/chore/cypress-container

**Comment by thekaveman** [comment]
Removing the `ON HOLD` label as we'll want to get this working again once #1263 and #1277 are in.

**Comment by afeld** [comment]
I forgot I looked into this a long time ago. [Using Cypress in interactive mode in Docker requires X11](https://www.cypress.io/blog/2019/05/02/run-cypress-with-a-single-docker-command/#Interactive-mode), which I can almost guarantee is more trouble than [the current setup](https://docs.calitp.org/benefits/tests/#running), especially across operating systems. I suggest closing this ticket.

**Comment by thekaveman** [comment]
I think we still want to look into this - not worried so much about getting a complete Cypress graphical interface (requiring X11) - but just being able to run the tests without local NPM madness. Sounds like @angela-tran had a good process working, we'll keep going from there.

**Comment by angela-tran** [comment]
This feels shaped enough, just not sure if we need to do it soon. This opens up a larger question of: what should our Cypress tests be covering?

**Comment by thekaveman** [comment]
We decided this effort isn't worth it right now. We're going to revisit the idea of these types of UI/UX tests in the near future.
