### ISSUE TITLE
Clean up Django .po files

### ISSUE THREAD

**Issue by machikoyasuda** [cal-itp/benefits#776]
The purpose of this ticket is to clean up our naming conventions and names on the msgIDs for the Django .po files. 

- [x] Remove `dmv` `mst`
- [x] Perhaps rename `oauth` to something more descriptive? Or document what path `oauth` refers to
- [x] Come up with a better naming system for the current `mst` (courtesy card) flow pages

**Comment by angela-tran** [comment]
I have some additional ideas on cleaning up our process around .po files:

1. I'd like for us to have a workflow that makes use of Django's `makemessages` utility. It seems like we lost that when we had to move some `msgid`s to our fixtures since running `makemessages` would comment out the ones that it can't see in our fixtures. One solution could be to have separate PO files for the fixture `msgid`s and have a script that combines those with the result of `makemessages`.
2. Avoid reusing `msgid`s. Even if the content is the same, we should define a separate `msgid`/`msgstr` entry so that reading through template files and .PO files is easier. One example of a confusing re-usage is [`agency_index.p[3]` on the `eligibility/start.html` template](https://github.com/cal-itp/benefits/pull/664#discussion_r897226484).

**Comment by machikoyasuda** [comment]
Use `mst_cc` for new CC copy

**Comment by machikoyasuda** [comment]
Closing - Addressed in https://github.com/cal-itp/benefits/pull/958 https://github.com/cal-itp/benefits/pull/966 https://github.com/cal-itp/benefits/pull/969
