### ISSUE TITLE
Make all pages 1-column

### ISSUE THREAD

**Issue by machikoyasuda** [cal-itp/benefits#933]
A clear and concise description of the task.

## Acceptance Criteria

- [ ] Make all pages one column

## Additional context

- Affects all pages

**Comment by srhhnry** [comment]
Design motivation for this task: The transition to one column from the previous two column design provides three important design updates for the Benefits app:
- It orients the app toward a mobile-first design, wherein we are designing in a portrait orientation instead of a landscape orientation. This approach radically simplifies our design system allowing us to design with nearly all the same elements on either mobile or desktop. 
- It frees up the page to add more content/copy at a larger base typeface (18), which may better accommodate the older adults we serve. 
- It allows us to design with scroll in mind, which modernizes our screens.


Additionally the two column design showed the same image on each page, which repetitively conveyed to users the context of the app (to provide a contactless payment benefit). Users don't need to see that context on each page to be reminded of their purpose for being on the site. Instead, the one column design includes a hero image on the home page that sets the context, which is reflective of modern design practices and understanding user needs.
