### ISSUE TITLE
Mock-up new Help page with sidebar navigation (alignment with MobiMart designs)

### ISSUE THREAD

**Issue by machikoyasuda** [cal-itp/benefits#977]
- [x] Create desktop screens in Figma
- [x] Create mobile screens in Figma
- [x] This is the time for any new copy additions! (e.g. ask about payment card names)
- [x] Add in copy per #1136 
- [x] Review designs with product
- [ ] Handoff to engineering

**Comment by srhhnry** [comment]
Progress: 



![Image](https://user-images.githubusercontent.com/5394204/198164794-ada1c096-dbf3-4b9f-9b2a-da256345a743.png)

**Comment by vykster** [comment]
@srhhnry to schedule a mini kickoff in January.

**Comment by vykster** [comment]
@srhhnry were you able to schedule a discussion on this?

**Comment by srhhnry** [comment]
Yup! That was the Help Page Workshop we had last week. The outcome includes several new steps for design (see this Slack comment: https://cal-itp.slack.com/archives/C013W8RUAMU/p1674599548410879). The overarching summary of that meeting is that we should pare this page down as much as possible (e.g. look for opportunities to include Help page information in the appropriate part of the flow, look for opportunities to possibly turn over control of copy of a page to an agency, look for opportunities to add illustration instead of relying solely on copy). 

I believe we'll revisit this page design, but I'm not yet sure if we want to do a round of edits on the copy first, or if that matters. I do believe this design very much aligns with our newly established views on Help and will likely move forward. I was thinking we could discuss during Feb sprint planning.

**Comment by srhhnry** [comment]
Update: Dev won't have bandwidth to create a new Help UI component for a few sprints, so putting this back in backlog for now.

**Comment by srhhnry** [comment]
Update: New copy work has created a need for design to revisit this component and update it based on line length

**Comment by srhhnry** [comment]
New designs can be [seen here](https://www.figma.com/file/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(Full-Application)?type=design&node-id=9639-53248)

@indexing Feel free to review copy/UI and make edits/suggestions. This ToC component was originally created for MobiMart and has section headers that are useful there. I used the section headers here to demarcate Cal-ITP Benefits info vs. Login info vs. Agency info. It's worth noting that when a user has selected an agency they will see that agency info in the home page, but if they click Help _before_ selecting an agency then that section will not appear to the user. 

I'll take another pass for cleaning up pixels/reviewing the copy on Monday. I might also want to make an instance for tablet (or larger mobile phone, to demonstrate how the component scales horizontally.

**Comment by srhhnry** [comment]
@indexing Designs/copy are ready for review.

**Comment by srhhnry** [comment]
Sarah to add a two line ToC item for reference

**Comment by srhhnry** [comment]
Added two line ToC item and moving this to backlog for implementation at a later point

**Comment by machikoyasuda** [comment]
Closing for now
May revisit next year
